Repository nasa/sch_lab, pull requests merged in 2020-08, with the labels that each got.

#47 Close #46, Add build number and baseline
  fsw/src/sch_lab_app.c
  fsw/src/sch_lab_version.h
Labels: CCB-FastTrack, IC-20200729

#48 Integration candidate 2020-07-29
  README.md
  fsw/src/sch_lab_app.c
  fsw/src/sch_lab_table.c
  fsw/src/sch_lab_version.h
Labels: IC-20200729

#50 Fix #49, reorg schedule table to conform with std
  CMakeLists.txt
  fsw/platform_inc/sch_lab_table.h
  fsw/src/sch_lab_app.c
  fsw/tables/sch_lab_table.c
Labels: CCB-20200819, CCB-READY, IC-20200819, code reviewed

#52 Integration Candidate: 2020-08-19
  CMakeLists.txt
  README.md
  fsw/platform_inc/sch_lab_table.h
  fsw/src/sch_lab_app.c
  fsw/src/sch_lab_version.h
  fsw/tables/sch_lab_table.c
Labels: IC-20200819

#51 Fix #20, Add header guard to sch_lab_sched_tab.h
  fsw/platform_inc/sch_lab_table.h
Labels: CCB-20200826, CCB-FastTrack, IC-20200826, code reviewed, enhancement
