Repository nasa/sch_lab, pull requests merged in 2020-12, with the labels that each got.

#55 Fix #54, Use MSG APIs
  fsw/src/sch_lab_app.c
Labels: CCB-20201112, IC-20201117

#57 Fix #56, Apply alignment pattern
  fsw/src/sch_lab_app.c
  fsw/src/sch_lab_version.h
Labels: CCB-20201202, IC-20201208, dependency

#59 sch_lab Integration Candidate: 2020-12-08
  README.md
  fsw/src/sch_lab_app.c
  fsw/src/sch_lab_version.h
Labels: IC-20201208
